SciNim/Unchained

- changelog.org
- src/unchained/units.nim
Adds experimental natural unit conversions (only SI ↦ natural) for the typical high energy physics convention based on Lorentz-Heaviside units.
> Experimental unit support, add Tesla

- changelog.org
- src/unchained/units.nim
- tests/tunchained.nim
We missed supporting the obvious way to write pound force. :)
> Fix pound-force parsing bug

- changelog.org
- src/unchained/units.nim
- tests/tunchained.nim
As the macro only had one generic argument, there was no way to have two "different" types that are actually similar.
> Fix equality using `==`

- src/unchained/units.nim
- tests/tunchained.nim
Fixes the issues with radians encountered in https://github.com/SciNim/getting-started/pull/30/.
It is fixed by first of all correcting the ordering of units. Higher powers are considered *lower* precedence, as they should appear before lower powers (to keep fractional logic).
Then makes radian and steradian distinct meter based units to avoid conversions in simple additive maths.
> Fix unit ordering and radian / steradian computations

- changelog.org
- src/unchained/units.nim
- tests/tresolveAlias.nim
- tests/tunchained.nim
Pretty self explanatory. Bq as a unit for activity of a radioactive source.
> Add Becquerel (Bq) as a unit for activity

- changelog.org
- src/unchained/units.nim
- tests/tunchained.nim
If a compound unit had an SI prefix and was involved in math that forced a conversion to its base type, the SI prefix of the compound was dropped.
In addition the SI prefix generation of units that used the `exclude` feature, were partially wrong, because the short and long names were mapped incorrectly.
> Fixes to math involving SI prefixes of compound units

- random_thoughts_and_todos.org
- src/unchained.nim
- src/unchained/core_types.nim
- src/unchained/quantities.nim
- src/unchained/units.nim
- src/unchained/utils.nim
This is a further step towards #8.
Instead of manually writing all quantities, the "type classes" of them and the `QuantityKind` enum, we now generate everything related to that from a single macro call. It's one more step towards a more general approach to define units systems.
The next step from here (as "outlined" in the updated 'thoughts' org file) is a declarative approach to the units themselves. This will save significantly more work than the quantity part.
> Quantities from a declarative macro

- src/unchained/constants.nim
- src/unchained/macro_utils.nim
- tests/tunchained.nim
Finally fixes the underlying issue of #5. The problem was simply that our quick check if the input is `UnitLess` was flawed for `const` variables, as their node kind is still an `nnkFloatLit`.
> Fix type information loss with `const` variable, fixes #5

- changelog.org
- src/unchained/units.nim
The generics of the `to` procedure were unconstrained. Matched also types that it shouldn't resulting in an (almost) endless loop.
> Fix signature of `to` procedure

- changelog.org
- src/unchained/define_units.nim
- src/unchained/units.nim
- tests/tunchained.nim
Fixes issue #29, which appeared because we lacked a single test that combines an SI and an imperial unit under `*` or `/`.
> Fix missing conversions between base and derived units

- changelog.org
- src/unchained/define_units.nim
- src/unchained/units.nim
- src/unchained/utils.nim
- tests/tunchained.nim
Previously this macro was a bit too dumb and only worked for powers `>= 2`. For smaller and negative values it produced rubbish.
edit: 
Also makes the string representation use a half-width space between number and unit by default. Can be disabled by compiling with `-d:noUnicode`, which also disables usage of unicode in the printing of the unit names.
Finally, changes the default behavior of unit printing from long format to short format for more concise output.
Use `pretty` manually to hand `short = false` if the previous behavior was preferred or compile with `-d:ShortFormat=false`.
> Improve custom `^` macro 

- README.org
- changelog.org
- src/unchained/api.nim
- src/unchained/define_units.nim
- src/unchained/macro_utils.nim
- src/unchained/quantities.nim
- src/unchained/si_units.nim
- src/unchained/units.nim
- src/unchained/utils.nim
- tests/tresolveAlias.nim
- tests/tunchained.nim
Adds each quantity as a `concept` so that they can be used to match types in procedure arguments:
```nim
proc force[M: Mass; A: Acceleration](m: M, a: A): Force = m * a
```
(or combine with explicit return type and a `.to(Foo)` call to get a specific type back.
edit: 
*Important note*: Using implicit generics involving these quantity concepts **is not supported**, because due to some limitation we can't extract the underlying type from these generics in the common use cases. Might be a simple upstream bugfix away though.
edit 2: ended up adding a bunch more things, a few possibly breaking (for certain use cases some things behave differently now).
Full changelog:
```
* v0.3.0
- concepts for each quantity to match different units of same quantity
in procedure calls!
- ~<~ for CT units now …
```
> Add quantity concepts

- changelog.org
- src/unchained/core_types.nim
- src/unchained/ct_unit_types.nim
- src/unchained/define_units.nim
- src/unchained/macro_utils.nim
- src/unchained/parse_units.nim
- src/unchained/si_units.nim
- src/unchained/units.nim
- src/unchained/utils.nim
- unchained.nimble
Adds the option to change the float size used in bytes. 4 and 8 bytes supported. Fixes #35.
```
* v0.3.2
- add ~FloatBytes~ ~intdefine~ variable, which allows to change the
underlying float type used at CT using ~-d:FloatBytes=4~.
Note: it might be advisable to also change the precision used to
compare two units using ~-d:UnitCompareEpsilon=~ and setting it to
some smaller value. Default is 8 corresponding to an epsilon of
~1e-8~.
Further, using ~float32~ can be problematic if used in combination
with very low / very high SI prefixes due to the lower precision available.
```
> Allow float size to change at CT via `-d:FloatBytes=4|8`

- src/unchained/define_units.nim
- src/unchained/units.nim
- tests/tunchained.nim
We now emit long names again for the units in `to`. This is not an issue anymore, as we fully alias all short and long units that are constructed and take care to generate the short string name by default.
Also work around a weird bug as mentioned in the commit message / comment in code.
> Fix `min` issue due to emitting `short` unit names

- src/unchained/units.nim
- tests/tunchained.nim
Works around the following:
```nim
defUnit(ft²•ft⁻³)
let x = 1.m⁻¹
check x.to(ft²•ft⁻³) == 0.3048.ft⁻¹
check x.to(ft²•ft⁻³) == 0.3048.ft²•ft⁻³
```
now producing problems as we emit the long form of user given types later. Those were not defined, because we only define long versions of the *reduced* version, i.e. `Foot⁻¹`.
> emit short and long versions of user given types

- changelog.org
- src/unchained/macro_utils.nim
- src/unchained/si_units.nim
- tests/tunchained.nim
Slight improvement to extraction of type information for aliases when looking at a typed bracket expression (e.g. `X[idx]` of fields of `unchained` types).
Update:
- further improved the type extraction also for slightly other cases of using `mapIt` for type conversion.
- add `Erg` as a unit
> improve type extraction for aliases

- changelog.org
- src/unchained/si_units.nim
Note the change to the definition of 1 year!
```
* v0.3.8
- add some more astronomical units:
- ~AstronomicalUnit~, ~AU~
- ~LightYear~, ~ly~
- ~Parsec~, ~parsec~ (not ~pc~ due to pico coulomb)
- add degree related units:
- ~ArcMinute~, ~arcmin~
- ~ArcSecond~, ~arcsec~
- *BREAKING*: Change definition of 1 year from 365 days to 365.25 days
(1 Julian year), matching definition of a light year. Otherwise they
would disagree if computed "by hand" using our units.  More precise,
but of course highly dependent on your calendar / definitions
-> For these time units it would probably be best to have different sets of units
/ unit systems, i.e. GregorianYear etc.
Anyone dealing with time units should be aware that these things are
tricky and best be dealt with _given their specific application_! …
```
> Some more astronomical units & arc units

- changelog.org
- src/unchained/ct_unit_types.nim
- src/unchained/define_units.nim
Caching names of units was an idea to _improve_ performance when many units were reused. But it turns out it's actually 50% slower, ouch!
> Do not cache string names of units anymore

- src/unchained/macro_utils.nim
`resolveTypeFromDistinct` calls `getImpl` on the distinct type which yields an `nkTypeDef` node of the original distinct type declaration, and returns the first child of the node, what would normally be the type name.
Normally when a type is exported its name in the AST becomes an `nkPostfix` node, however due to a [Nim bug](https://github.com/nim-lang/Nim/issues/22933) this node was not saved in typed AST and the first child was always the type symbol node. If the bug in Nim is fixed, `resolveTypeFromDistinct` has to skip the postfix node here.
> skip postfix node when resolving distinct type from impl AST

- changelog.org
- src/unchained/constants.nim
- src/unchained/define_units.nim
- src/unchained/si_units.nim
- src/unchained/units.nim
Some minor changes, with one breaking change. Renaming `G` for Gauss to `gauss`, due to potential problems with Giga SI prefix. 
The version bump to `v0.4.0` is mainly as this is the state used for the results in my thesis.
Full changelog:
```
* v0.4.0
- add unit of ~Barn~
- BREAKING: rename short form of Gauss to ~gauss~. Single capital ~G~
is too brittle combined with Giga prefix
- improve printed unit names in error messages
- add hbar as a constant
- add note about natural unit convention used
```
> Add `Barn`, improved error messages

- src/unchained/parse_units.nim
- tests/tunchained.nim
Fixes the issue by raising a CT error in case the given prefix does not make any sense.
> Fix unit parsing including bad prefixes, closes #48

- .github/workflows/ci.yml
- changelog.org
- src/unchained/units.nim
- unchained.nimble
This is to guarantee the property `x.to(T) is T` always holds. This is needed in Measuremancer's `FloatLike` concept.
> Improve `to` to use exact type as given by the user
